spring:
  datasource:
#    url: "jdbc:postgresql://db:5432/postgres"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "U9]zCd(-3Uk4~<|G"
  jpa:
    properties:
      hibernate:
        default_schema: "the_cooking_pot"
        jdbc.lob:
          non_contextual_creation: true
  mail:
    host: "relay.plus.net"
    port: 587
    username: "REDACTED"
    password: "REDACTED"
    properties:
      mail:
        smtp:
          auth: true
  security:
    oauth2:
      client:
        registration:
          recipe-auth:
            client-id: "recipe-application"
            client-secret: "recipe-application"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          recipe-auth:
            authorization-uri: http://localhost:8085/authorize
            token-uri: http://localhost:8085/token
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8085/.well-known/jwks.json