spring:
  datasource:
#    url: "jdbc:postgresql://db:5432/postgres"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "U9]zCd(-3Uk4~<|G"
  jpa:
    properties:
      hibernate:
        default_schema: "the_cooking_pot"
        jdbc.lob:
          non_contextual_creation: true
  mail:
    host: "relay.plus.net"
    port: 587
    username: "scarfebread"
    password: ",9)+0da#6ome6Fu?"
    properties:
      mail:
        smtp:
          auth: true
oauth:
  okta:
    client_id: "0oa7e1anmiOgPajIx5d6"
    client_secret: "2d2iybNvUus0mU4f3Fip1Vn97mQRVCmsL-MU5tL3"
    redirect_uri: "http://localhost:8080/auth/okta-redirect"
    token_endpoint: "https://dev-25996170.okta.com/oauth2/default/v1/token"
    auth_endpoint: "https://dev-25996170.okta.com/oauth2/default/v1/authorize"
    pkce_challenge_method: "S256"
